FROM php:8.2-fpm

# Install dependencies
RUN apt-get update --fix-missing
RUN apt-get install -y curl git cron supervisor libssl-dev libpng-dev libz-dev libpq-dev libzip-dev libjpeg-dev libmemcached-dev unzip zip redis-server mariadb-server libgmp-dev

# Install PHP GMP extension
RUN docker-php-ext-install gmp

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions pdo pdo_mysql mysqli gd exif zip mcrypt mbstring openssl pcntl memcached

#imagick
RUN apt-get update && apt-get install -y \
    libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
	&& docker-php-ext-enable imagick

# Install npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest

# Install redis
#RUN pecl install redis
#RUN docker-php-ext-enable redis

# Install composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Install ffmpeg
RUN apt-get install -y ffmpeg

# Clear cache
RUN apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /var/www/html

# copy supervisor config and run it
#COPY ./core-service/src/docker-local/php/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#COPY ./docker-local/php/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Add the cron job
#COPY ./cron /etc/cron.d/core-microservice-cron
#RUN chmod 0644 /etc/cron.d/core-microservice-cron
#RUN crontab /etc/cron.d/core-microservice-cron

# Copy code to /var/www/html
COPY . .

#todo - finish it - docker php
# WORKDIR /var/www/html/tokenlite_app
# run composer install
# ENV COMPOSER_ALLOW_SUPERUSER=1
# RUN composer install && npm install

# Set up runtime configurations (e.g., supervisord, cron jobs)
#COPY ./docker-local/php/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#COPY ./cron /etc/cron.d/core-microservice-cron
#RUN chmod 0644 /etc/cron.d/core-microservice-cron
#RUN crontab /etc/cron.d/core-microservice-cron

# Add a command to auto-update the .env file if necessary
#CMD ["some_command_to_update_env"]